//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registeration_Login_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int userID { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public Nullable<int> age { get; set; }
        public string gender { get; set; }
        public string phone_number { get; set; }
        public string city { get; set; }
    }
}
